name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml

  publish:
    name: Build and publish package to PyPI
    needs: run-tests  # Requires tests to pass
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    # v8.1.0
    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
    - run: uv build
    - run: uv publish
